# this file is added to demo how configs could be set in .yaml, comparing to application.properties

#server:
#  port: '5050'
#welcome:
#  message: Welcome to Spring/Spring Boot full feature demo application

#spring:
#  datasource:
#    username: sa
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    password: password
#  h2:
#    console:
#      settings:
#        web-allow-others: 'true'
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
